version: "3.8"

services:
  # 1. Relational Database
  postgres:
    image: postgres:16-alpine
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. In-Memory Cache
  redis:
    image: redis:7-alpine
    container_name: dev_redis
    restart: always
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data

  # 3. Message Broker with Management UI
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dev_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5674:5672" # AMQP protocol port
      - "15674:15672" # Web Dashboard (http://localhost:15672)

  # 4. Metrics Collector
  prometheus:
    image: prom/prometheus:latest
    container_name: dev_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 5. Dashboard Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: dev_grafana
    restart: always
    ports:
      - "3000:3000" # Web Dashboard (http://localhost:3000)
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  grafana_data:
